### ISSUE TITLE
About ablation study

### ISSUE THREAD

**Issue by jkli-aa** [nirat1606/OADis#1]
Thanks for your nice work for czsl :).
I am very confused about the results of the ablation experiments. It seems that OADis achieves SOTA performance on MIT-States with merely $L_{cls}$. I would appreciate if you could address my concern.
Looking forward to your reply.

**Comment by nirat1606** [comment]
Hi, Thank you for your interest in our work. We do some novel additions in our base architecture, by using cosine similarity before softmax and object-conditioned network for word embeddings, which result in performance increase than previous baselines. Although, the increment is not significant, hence we add novel losses as well. Hope this is helpful.

**Comment by nirat1606** [comment]
No further comments, hence closing this issue
