### ISSUE TITLE
about supplemental

### ISSUE THREAD

**Issue by hannajiang** [nirat1606/OADis#3]
Hello, thanks for your excellent works, could you give me the link of supplemental? I find it in [https://openaccess.thecvf.com/content/CVPR2022/supplemental/Saini_Disentangling_Visual_Embeddings_CVPR_2022_supplemental.pdf](url), but it is same with original paper.

**Comment by nirat1606** [comment]
Hi, Thanks for pointing it out. We will get that corrected on the CVF open access website. Till that time, you can use the link on our website: https://www.cs.umd.edu/~nirat/OADis/ for finding the correct pdf for supplementary material.

**Comment by nirat1606** [comment]
Bug reported to CVF
