### ISSUE TITLE
missing file lemmatize_liberally.py

### ISSUE THREAD

**Issue by hamed-d** [nirat1606/OADis#5]
Hello, thanks for sharing your work. The notebook named vaw-dataset.ipynb in the VAW-CZSL folder on drive has an import of a file named lemmatize_liberally.py. I could not find this anywhere. Where can I get this?

Thanks

**Comment by nirat1606** [comment]
Hi, Thank you for pointing that out. Added the file in utils folder now. Let me know if you still run into issues!

**Comment by hamed-d** [comment]
Thanks for adding the file. When running the test code I bump into some issues with loading the checkpoint file. Is there supposed to be a pth file for vaw-czsl which is missing or should I use the mit checkpoint for that dataset?
